theme = "dark_plus_transparent"

[editor]
auto-format = true
cursorline = false
mouse = false
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "error"

[keys.insert]
# Unreakable CTRL+S saving habit
C-s = [":write", "normal_mode"]

[keys.normal]
# Unreakable CTRL+S saving habit
C-s = ":write"
# vim habit
G = "goto_file_end"
